# Auto-labeling configuration for PRs based on changed files

# Frontend changes
'frontend':
  - 'apps/web/**/*'
  - '*.tsx'
  - '*.jsx'

# Backend changes
'backend':
  - 'apps/server/**/*'
  - '*.ts'
  - '!*.tsx'

# Database changes
'database':
  - 'packages/database/**/*'
  - '**/prisma/**/*'
  - '**/*.sql'
  - '**/migrations/**/*'

# Docker changes
'docker':
  - 'Dockerfile'
  - 'docker-compose*.yml'
  - '.dockerignore'
  - 'scripts/docker-*.sh'

# CI/CD changes
'ci/cd':
  - '.github/workflows/**/*'
  - '.github/actions/**/*'

# Documentation changes
'documentation':
  - '*.md'
  - 'docs/**/*'
  - '.github/README.md'

# Configuration changes
'config':
  - '*.json'
  - '*.yml'
  - '*.yaml'
  - '*.toml'
  - '*.config.*'
  - 'tsconfig*.json'
  - 'package.json'
  - 'pnpm-lock.yaml'

# Dependencies
'dependencies':
  - 'package.json'
  - 'pnpm-lock.yaml'
  - '**/package.json'

# Testing
'testing':
  - '**/*.test.*'
  - '**/*.spec.*'
  - '**/test/**/*'
  - '**/tests/**/*'

# Shared packages
'shared':
  - 'packages/**/*'

# Types
'types':
  - 'packages/shared-types/**/*'
  - '**/*.d.ts'
  - '**/types/**/*'

# UI components
'ui':
  - 'packages/ui/**/*'
  - '**/components/**/*'

# Security
'security':
  - '.github/workflows/codeql.yml'
  - '.github/workflows/security.yml'
  - '**/security/**/*'

# Performance
'performance':
  - '**/performance/**/*'
  - '**/*.perf.*'

# Bug fix
'bug':
  - any: ['fix', 'bug', 'hotfix']

# Feature
'feature':
  - any: ['feat', 'feature']

# Refactor
'refactor':
  - any: ['refactor', 'refact']

# Chore
'chore':
  - any: ['chore', 'maintenance']
