name: Maintenance

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  # Job 1: Update Dependencies
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'

      - name: Update dependencies
        run: |
          pnpm update --recursive
          pnpm install

      - name: Run tests after update
        run: |
          pnpm lint
          pnpm check-types
          pnpm build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            ## Dependency Updates
            
            This PR updates all dependencies to their latest versions.
            
            ### Changes
            - Updated all npm packages to latest versions
            - Verified build and type checking still works
            
            ### Testing
            - [x] Lint passes
            - [x] Type checking passes
            - [x] Build succeeds
            
            Please review and test thoroughly before merging.
          branch: chore/update-dependencies
          delete-branch: true

  # Job 2: Clean up old workflow runs
  cleanup-runs:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 10

  # Job 3: Clean up old Docker images
  cleanup-images:
    name: Cleanup Old Docker Images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'server'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: true

      - name: Delete old web container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'web'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: true
